In [2]:
import pandas as pd

df = pd.read_csv('TaiwanSpecies20200427_UTF8.csv',  escapechar='\\', encoding='utf-8')

# print basic csv info
print (df.info())

# display first 5 rows
display(df.head())

# only get 2 columns
df2 = df[['name', 'family_c']]
display(df2)

df2.to_csv('output.csv')

/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (17,18,20,21,29,30,31,36,37) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154798 entries, 0 to 154797
Data columns (total 38 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   kingdom               154798 non-null  object
 1   kingdom_c             154798 non-null  object
 2   phylum                154306 non-null  object
 3   phylum_c              154305 non-null  object
 4   class                 154201 non-null  object
 5   class_c               154198 non-null  object
 6   order                 154236 non-null  object
 7   order_c               154162 non-null  object
 8   family                152472 non-null  object
 9   family_c              150853 non-null  object
 10  name_code             154798 non-null  object
 11  name                  154798 non-null  object
 12  genus                 154798 non-null  object
 13  genus_c               98582 non-null   object
 14  species               154796 non-null  object
 15  infraspecies_marker   16964 non-null   object
 16  infraspecies          19590 non-null   object
 17  infraspecies2_marker  43 non-null      object
 18  infraspecies2         43 non-null      object
 19  author                152357 non-null  object
 20  author2               1127 non-null    object
 21  accepted_name_code    154796 non-null  object
 22  status_id             154588 non-null  float64
 23  is_accepted_name      154798 non-null  int64
 24  is_endemic            127239 non-null  float64
 25  is_marine             14025 non-null   float64
 26  alien_status          127386 non-null  float64
 27  is_fossil             117447 non-null  float64
 28  common_name_c         43035 non-null   object
 29  redlist_wang          1571 non-null    object
 30  redlist_wang_ass      1193 non-null    object
 31  redlist_chen          53 non-null      object
 32  iucn_code             4361 non-null    object
 33  iucn_assessment       409 non-null     object
 34  iucn_dateassessed     4360 non-null    object
 35  iucn_id               4359 non-null    float64
 36  coa_redlist_code      275 non-null     object
 37  cites_code            1169 non-null    object
dtypes: float64(6), int64(1), object(31)
memory usage: 44.9+ MB
None

,kingdom,kingdom_c,phylum,phylum_c,class,class_c,order,order_c,family,family_c,...,common_name_c,redlist_wang,redlist_wang_ass,redlist_chen,iucn_code,iucn_assessment,iucn_dateassessed,iucn_id,coa_redlist_code,cites_code
0,Viruses,病毒,NaN,NaN,NaN,NaN,dsDNA,雙鏈DNA病毒,Iridoviridae,虹彩病毒科,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Viruses,病毒,NaN,NaN,NaN,NaN,dsDNA,雙鏈DNA病毒,Iridoviridae,虹彩病毒科,...,魚淋巴囊泡症,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Viruses,病毒,NaN,NaN,NaN,NaN,dsDNA,雙鏈DNA病毒,Iridoviridae,虹彩病毒科,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Viruses,病毒,NaN,NaN,NaN,NaN,dsDNA,雙鏈DNA病毒,Iridoviridae,虹彩病毒科,...,臺灣石斑虹彩病毒,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Viruses,病毒,NaN,NaN,NaN,NaN,dsDNA,雙鏈DNA病毒,Iridoviridae,虹彩病毒科,...,魚流行性造血組織壞死魚,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

                                                    name family_c
0                        Lymphocystivirus Flounder virus    虹彩病毒科
1                  Lymphocystivirus Lymphocystis disease    虹彩病毒科
2                           unclassed Goldfish virus 1-2    虹彩病毒科
3           Megalocytivirus Grouper Iridovirus of Taiwan    虹彩病毒科
4       Ranavirus Enzootic haematopoietic necrosis virus    虹彩病毒科
...                                                  ...      ...
154793                                   Cirsium vulgare       菊科
154794                                 Apocopis wrightii      禾本科
154795           Pedicularis refracta transmorrisonensis      列當科
154796                    Pedicularis transmorrisonensis      列當科
154797                           Steccherinum formosanum     齒耳菌科

[154798 rows x 2 columns]